
server:
  port: 8080

spring:
  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 200MB
  datasource:
    username: root
    password: shehuinihuaye123#
    url: jdbc:mysql://43.163.199.224:3306/matchapp?useUnicode=true&characterEncoding=utf-8&useAffectedRows=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    port: 6379
    host: localhost
    password: 123456

token:
  header: Authorization
  secret: thisIsAAwSomeSecret12345
  expireTime: 600

mybatis-plus:
  type-aliases-package: com.awe.model.entity
  mapper-locations: classpath:mapper/*.xml
  configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

upload:
  mode: oss
  oss:
    url: http://awlewis-document-storage.oss-ap-northeast-1.aliyuncs.com/
    endpoint: oss-ap-northeast-1.aliyuncs.com
    accessKeyId: LTAI5tJCGYd6TssE2ceFQKFT
    accessKeySecret: 7S4ElhDduVZfqvn9EezIHKKTwTcBtU
    bucketName: awlewis-document-storage

logging:
  level:
    org.springframework.web: trace
    org.springframework.security: error
    org.mybatis: debug
  charset:
    console: UTF-8
    file: UTF-8
  file:
    name: log/ota.log
  logback:
    rollingpolicy:
      max-file-size: 1MB
      max-history: 30
      file-name-pattern: log/%d{yyyy-MM}/ota.%d{yyyy-MM-dd}.%i.log



