
server:
  port: 8080

spring:
  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 200MB
  datasource:
    username: 
    password: 
    url: 
    driver-class-name: 
    type: 
  redis:
    port: 6379
    host: localhost
    password: 

token:
  header: Authorization
  secret: thisIsAAwSomeSecret12345
  expireTime: 600

mybatis-plus:
  type-aliases-package: com.awe.model.entity
  mapper-locations: classpath:mapper/*.xml
  configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

upload:
  mode: oss
  oss:
    url: 
    endpoint: 
    accessKeyId: 
    accessKeySecret: 
    bucketName: 

logging:
  level:
    org.springframework.web: trace
    org.springframework.security: error
    org.mybatis: debug
  charset:
    console: UTF-8
    file: UTF-8
  file:
    name: log/ota.log
  logback:
    rollingpolicy:
      max-file-size: 1MB
      max-history: 30
      file-name-pattern: log/%d{yyyy-MM}/ota.%d{yyyy-MM-dd}.%i.log



